apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sneakers
  namespace: default
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: sneakers
    spec:
      hostNetwork: true
      volumes:
        - name: dockersock
          hostPath:
            path: /var/run/docker.sock
        - name: home
          hostPath:
            path: /home/root
      containers:
        - name: "drumstick"
          image: "iameli/drumstick-eli"
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: true
          volumeMounts:
            - name: home
              mountPath: /home/root
            - name: dockersock
              hostPath:
                path: /var/run/docker.sock
