apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: sneakers
  namespace: default
spec:
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        app: sneakers
    spec:
      volumes:
        - name: dockersock
          hostPath:
            path: /var/run/docker.sock
        - name: home
          hostPath:
            path: /home/root
      containers:
        - name: "drumstick"
          ports:
            - name: ssh
              containerPort: 22
              hostPort: 22
              protocol: TCP
          image: "iameli/drumstick-eli"
          imagePullPolicy: IfNotPresent
          securityContext:
            privileged: true
          volumeMounts:
            - name: home
              mountPath: /home/root
